### ISSUE TITLE
can't cd to /root/.cache/mainline/5.19.6

### ISSUE THREAD

**Issue by nodje** [bkw777/mainline#154]
I feel sorry to have to fill in an Issue for something that sounds very basic, but I'm just unable to use the cli to install the latest kernel.

There are only few options listed in the --help menu, I've tried them all, but none seem to fill in /root/.cache/mainline with the kernel availables.

--check returns latest as being 5.19.6
--list doesn't return anything
--install-latest ends up in the error can't cd to /root/.cache/mainline/5.19.6

--download 15.9.6 doesn't seem to do anything
--install 5.19.6 also ends up in the cd error.

It seems I need to sync .cache/mainline with all kernel options available but I can't see how to do this.

I'm on Ubuntu 22.04.01

**Comment by jagiella** [comment]
same problem here, running on Ubuntu 22.10

**Comment by nodje** [comment]
Thanks! 
Glad you found out.

Then it's a bug really. I don't think there's anything I can do to get it fixed with the actual 1.0.15 version using CLI

**Comment by bkw777** [comment]
Dupe of #147
Update to 1.0.16 or adjust show-previous-N-majors as you have already discovered.
5.19.6 and .7 don't exist, as you have also already discovered.

**Comment by jagiella** [comment]
Updating to 1.0.16 does not solve the issue. I have 1.0.16 installed and it still only shows the already installed 5.x kernels and the 6.0.0-rc3 kernel.

![image](https://user-images.githubusercontent.com/4679834/190895650-994c8853-a1f4-4b23-8f57-daffbcc3aa4f.png)

Only increasing `show-previous-N-majors` solves it.
